package main

import (
	"context"
	"fmt"
	spotifyauth "github.com/zmb3/spotify/v2/auth"
	"log"
	"net/http"
	"os"

	"github.com/zmb3/spotify/v2"
)

const redirectURI = "http://localhost:8080/callback"

var (
	auth = spotifyauth.New(
		spotifyauth.WithRedirectURL(redirectURI),
		spotifyauth.WithScopes(spotifyauth.ScopePlaylistModifyPrivate, spotifyauth.ScopePlaylistModifyPublic),
	)
	ch    = make(chan *spotify.Client)
	state = "abc123"
)

func main() {
	var client *spotify.Client

	http.HandleFunc("/callback", completeAuth)

	go func() {
		url := auth.AuthURL(state)
		fmt.Println("Please log in to Spotify by visiting the following page in your browser:", url)

		// wait for auth to complete
		client = <-ch

		// use the client to make calls that require authorization
		user, err := client.CurrentUser(context.Background())
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println("You are logged in as:", user.ID)
		ctx := context.Background()
		playlistId := spotify.ID(os.Getenv("SPOTIFY_PLAYLIST_ID"))
		//Get input playlist
		playlist := getPlaylist(ctx, client, playlistId)
		fmt.Println("Playlist retrieved:", playlist)
		//Get each track
		originalTracks := getFullTracksFromPlaylist(ctx, client, playlist)
		fmt.Println("Tracks retrieved:", originalTracks)

		programMode := os.Getenv("PROGRAM_MODE")

		finalTracks := getFinalPlaylistTracks(ctx, client, originalTracks, programMode)
		//Create playlist
		createPlaylist(ctx, client, user, finalTracks)

		os.Exit(0)
	}()

	http.ListenAndServe(":8080", nil)

}

func completeAuth(w http.ResponseWriter, r *http.Request) {
	tok, err := auth.Token(r.Context(), state, r)
	if err != nil {
		http.Error(w, "Couldn't get token", http.StatusForbidden)
		log.Fatal(err)
	}
	if st := r.FormValue("state"); st != state {
		http.NotFound(w, r)
		log.Fatalf("State mismatch: %s != %s\n", st, state)
	}
	// use the token to get an authenticated client
	client := spotify.New(auth.Client(r.Context(), tok))
	w.Header().Set("Content-Type", "text/html")
	fmt.Fprintf(w, "Login Completed!")
	ch <- client
}

func getPlaylist(ctx context.Context, client *spotify.Client, playlistId spotify.ID) *spotify.FullPlaylist {
	fmt.Println("Beginning getPlaylist")

	playlist, err := client.GetPlaylist(ctx, playlistId)

	if err != nil {
		fmt.Println(err.Error)
	}
	fmt.Println(playlist.ID)
	return playlist
}

func getFullTracksFromPlaylist(ctx context.Context, client *spotify.Client, playlist *spotify.FullPlaylist) []spotify.FullTrack {
	fmt.Println("Beginning getFullTracksFromPlaylist")
	tracks := []spotify.FullTrack{}
	playlistTracks := playlist.Tracks.Tracks
	for _, playlistTrack := range playlistTracks {
		tracks = append(tracks, playlistTrack.Track)
	}
	return tracks
}

func getAlbum(ctx context.Context, client *spotify.Client, albumId spotify.ID) *spotify.FullAlbum {
	fmt.Println("Beginning getAlbum")
	album, err := client.GetAlbum(ctx, albumId)

	if err != nil {
		fmt.Println(err.Error)
	}
	fmt.Println(album.ID)
	return album
}

func createPlaylist(ctx context.Context, client *spotify.Client, user *spotify.PrivateUser, tracks []spotify.SimpleTrack) {
	fmt.Println("Beginning createPlaylist")

	playlistName := "AutogeneratedPlaylist"
	playlistDescription := "Created automatically"
	createPublicPlaylist := false
	collaborativePlaylist := false
	userId := user.ID

	createdPlaylist, err := client.CreatePlaylistForUser(ctx, userId, playlistName, playlistDescription, createPublicPlaylist, collaborativePlaylist)
	if err != nil {
		fmt.Println(err.Error)
	}
	playlistId := createdPlaylist.ID
	//Get track IDs from list of tracks
	var trackIds []spotify.ID
	for _, track := range tracks {
		trackIds = append(trackIds, track.ID)
	}
	_, err = client.AddTracksToPlaylist(ctx, playlistId, trackIds...)
	if err != nil {
		fmt.Println(err.Error)
	}
	fmt.Println("Playlist created")

}

func getFinalPlaylistTracks(ctx context.Context, client *spotify.Client, originalTracks []spotify.FullTrack, programMode string) []spotify.SimpleTrack {
	finalTracks := []spotify.SimpleTrack{}
	forbiddenSongs := []spotify.SimpleTrack{}

	//First we add every item on the list to the forbiddenSongs list
	for _, originalTrack := range originalTracks {
		forbiddenSongs = append(forbiddenSongs, originalTrack.SimpleTrack)
	}

	for _, originalTrack := range originalTracks {
		//Get album for each track, and the tracks from those albums
		albumId := originalTrack.Album.ID
		album := getAlbum(ctx, client, albumId)
		fmt.Println("Album retrieved:", album)
		albumTracklist := album.Tracks.Tracks
		switch programMode {
		case "ALL_BUT_ORIGINAL":
			//For each track on the album, add it to the final list if it isn't the original track
			for _, albumTrack := range albumTracklist {
				if albumTrack.ID != originalTrack.SimpleTrack.ID {
					finalTracks = append(finalTracks, albumTrack)
				}
			}
		case "ONE_TRACK_PER_TRACK":
			//Go through the rest of the album's tracks and test for acceptable songs (which order?)
			for _, albumTrack := range albumTracklist {
				if !isSongIDForbidden(forbiddenSongs, albumTrack) {
					finalTracks = append(finalTracks, albumTrack)
					//Also add the selected song to the forbidden list, so it doesn't get chosen again.
					forbiddenSongs = append(forbiddenSongs, albumTrack)
					break
				}
			}
		}
	}
	return finalTracks
}

func isSongIDForbidden(forbiddenSongs []spotify.SimpleTrack, song spotify.SimpleTrack) bool {
	return contains(forbiddenSongs, song)
}

func contains(s []spotify.SimpleTrack, e spotify.SimpleTrack) bool {
	for _, a := range s {
		if a.ID == e.ID {
			return true
		}
	}
	return false
}
